### ISSUE TITLE
Command 'onos config config set' and 'get' saves to ztp.yaml

### ISSUE THREAD

**Issue by SeanCondon** [onosproject/onos-cli#18]
The command to save CLI configuration attributes, such as:
* `onos config config set a b` OR
* `onos ztp config set c d` OR
* `onos topo config set e f`

all save the attribute to ~/.onos/ztp.yaml regardless of which subsystem is used

Even though a file is created per subsystem all attributes set in this way are saved in to ztp.yaml

I think this is because the set is going through a viper global variable, which points to the ZTP file rather than any others.

Also if you try to set an attribute on `config` is will not work until ztp.yaml exists.

I'm not really sure what this system was trying to achieve, so someone that does should tackle it

**Comment by SeanCondon** [comment]
We agreed to take this out since we don't have a solid use case for it at the moment

A PR will follow

**Comment by Andrea-Campanella** [comment]
@SeanCondon can we close ?

**Comment by SeanCondon** [comment]
Removed from onos-config and onos-topo - still there in onos-ztp but that's OK because it still works
